apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aeromap-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: 84.201.181.11.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-svc
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-svc
            port:
              number: 5000
