services:
  db:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      POSTGRES_USER: aviation_user
      POSTGRES_PASSWORD: aviation_pass
      POSTGRES_DB: aviation_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:  
    image: quay.io/keycloak/keycloak:25.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: http://keycloak:8080  # Добавлено: force iss to keycloak for consistency
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data

  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
      - keycloak  
    environment:
      DB_URL: postgresql://aviation_user:aviation_pass@db:5432/aviation_db
      OIDC_CLIENT_ID: aviation-api  
      OIDC_CLIENT_SECRET: 8HUnPbB26kdCImTFXLfN9scQLQmYLW4d  
      OIDC_ISSUER: http://keycloak:8080/realms/aviation-realm  
      SECRET_KEY: your-secret-key  

volumes:
  pgdata:
  keycloak_data:  